#version 300 es

in vec4 VERTEX_POS;
in vec2 BUFFER_RESOLUTION;
in vec2 OVERLAY_TEXTURE_POS;

out vec2 OVERLAY_TEXTURE_COORD;
out vec2 RESOLUTION;

void main() {
    gl_Position = VERTEX_POS;
    OVERLAY_TEXTURE_COORD = OVERLAY_TEXTURE_POS;
    RESOLUTION = BUFFER_RESOLUTION;
}